In [1]:
import sys
# for local development
RT_LIBS_PATH = "/Users/alex/Dev_projects/MyOwnRepo/rt_libs/src"
BA_LIBS_PATH = "/Users/alex/Dev_projects/MyOwnRepo/basic_application/src"
sys.path.append(RT_LIBS_PATH)
sys.path.append(BA_LIBS_PATH)

In [3]:
from data_providers import ClickHouseConnector
from data_providers import DbDataProviderRT5

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from train_tools import plot_and_go
from basic_application import with_debug_time

%matplotlib notebook
db_connect_params = {
    "host" : "217.197.116.177",
    "port" : 59000,
    "user" : "alex",
    "password" : "Xrxcmr758",
    "database" : "rt5"
}

In [4]:
import time
import numpy as np
import pandas as pd

## DatasetDownload

In [8]:
path = "/Users/alex/Dev_projects/RT/model_train/datasets/rt5/03.BTC_USDT-300-train.csv"
dataset = pd.read_csv(path, index_col='ts')
dataset.head()

,dt,lowest_ask,highest_bid,asks,bids,buy_vol,sell_vol,total_vol,buy_num,sell_num,total_num
ts,,,,,,,,,,,
1662185340,2022-09-03 06:09:00,19929.31,19928.361,"{'19929.31': 0.5, '19931.24': 0.25, '19932.14'...","{'19928.36': 0.25, '19926.23': 0.5, '19924.98'...",0.177276,0.164399,0.341675,9,10,19
1662185640,2022-09-03 06:14:00,19915.01,19913.000,"{'19915.01': 0.492324, '19920.6': 0.25, '19922...","{'19913': 0.25, '19911.03': 0.226976, '19910.9...",0.018660,0.091484,0.110144,6,10,16
1662185940,2022-09-03 06:19:00,19910.93,19908.920,"{'19910.93': 0.467253, '19913.63': 0.25, '1991...","{'19908.92': 0.25, '19906.6': 0.25, '19903.85'...",0.108600,0.187092,0.295692,9,7,16
1662186240,2022-09-03 06:24:00,19836.08,19826.230,"{'19836.08': 0.5, '19838.07': 0.25, '19845.43'...","{'19826.23': 0.25, '19825.24': 0.14, '19825.23...",0.548822,0.795283,1.344105,16,11,27
1662186540,2022-09-03 06:29:00,19859.43,19858.441,"{'19859.43': 0.5, '19865.16': 0.25, '19867.4':...","{'19858.44': 0.25, '19857.44': 0.5, '19855.44'...",0.374214,0.659355,1.033569,8,13,21

# DataPointV3

In [181]:

"""
Класс DataPoint реализован, чтобы передать текущее представление точки данных в core_v2.

Для обычных фичей достаточно методов get_value и get_values со стандартной длиной выборки, равной observation_len
В некоторых случаях, возможно, потребуется получать весь хвост данных, чтобы взять объективное среднее для нормализации.

Дополнительные методы типа get_current_index, и get_value со специфическим индексом нужны в фиче с историей.
И то - для текущей точки достаточно current_index, а в init'е - наверное, можно использовать относительное указание индекса

Т.к. пока нет необходимости работать с историей (сделал быстро вычисление на лету) - то достаточно двух базовых методов

Второй поинт - пока нет работы с future_points - отрицательную индексацию модно исключить. 
Это должно повысить производлительность, но, возможно, игра не стоит свеч и можно все оставить в одном классе, надо тестить.


Из этой реализации убраны некоторые методы, которые были в старой в силу их ненадобности.'
"""
import numpy as np

from basic_application import with_exception


class DataPointError(Exception):
    pass


class DataPoint:
    """DataPointV2, описание смотри в модуле."""
    def __init__(self, data, observation_len=5, future_points=0):
        self.data = data
        # Длина наблюдения. Для разных step_factor включает в себя разное количество точек данных.
        self.observation_len = observation_len
        # Количество точек данных в будущем 
        self.future_points = future_points
        # Количество точек данных, доступных для построения observation с учетом всех доступных step_factors
        self.tail_points = len(self.data) - self.future_points
        
        # В "абстрактных" тестовых сценариях присутствуют кейсы, где дата поинт состоит из одной точки. 
        # На синтетических и реальных данных такого нет, observation_len всегда больше 1
        if self.data.shape[0] > 1:
            self.period = data.index[1] - data.index[0]
        else:
            self.period = 1

        # Верхушка observation = текущая точка данных. 
        #Так это последняя точка данных, но future_points может ее сместить ближе к началу.
        self.cursor = data.shape[0] - self.future_points - 1  # Курсор про номер позии
        self.index = data.index.values[self.cursor]           # Индекс про индекс
        
    def _get_num(self, step_factor, num):
        "Вычисляет количество точек наблюдения и возволяет в большей части случаев исключить эту логику из потребителя"
        if num is None:
            # Базовый сценарий
            return self.observation_len 
        elif num == -1:
            # Вычисление позволяет передать максимальное количество точек для вычисления value со step_factor выше 1.
            return self.tail_points // (self.observation_len*step_factor) * (self.observation_len * step_factor)
        else:
            return num
        
    def get_index_slice(self, step_factor=1, num=None):
        """Возвращает все курсоры, в том числе расположенные между реперными точками"""
        num = self._get_num(step_factor, num)

        if num >= 0:
            # верхний индекс на единицу выше, т.к. это элемент не захватывается при слайсинге
            up_bound = self.cursor + 1
            low_bound = up_bound - num * step_factor
        else:
            # Отрицательные значения нужны при работе с future points. Надо протестить производительномть, можент быть выпилить эту часть.
            low_bound = self.cursor + 1
            up_bound = low_bound - num * step_factor
        return low_bound, up_bound
            
    def get_values(self, name, step_factor=1, num=None, agg="average"):
        """Возвращает значений точек данных заданной длины и агрегированное для step_factor выше 1
        """
        num = self._get_num(step_factor, num)
        values = self.data.loc[:, name].values
        low_bound, up_bound = self.get_index_slice(step_factor=step_factor, num=num)
        values = values[low_bound : up_bound]
        if step_factor > 1:
            # небольшая оптимизация производительности
            values = getattr(np, agg)(values.reshape(-1, step_factor), axis=1)
        return values
    
    def get_value(self, name, step_factor=1, agg="average"):
        """Метод возвращает одно значение агрегированное для step_factor выше 1"""
        value = self.get_values(name, step_factor=step_factor, agg=agg, num=1)
        return value[0]
    
    def get_value_by_idx(self, name, idx, step_factor=1, agg="average"):
        """
        Метод возвращает одно значение агрегированное для step_factor выше 1 по индексу
        Метод нужен только в сценарии рассчета фичи с историей хранения (для инициализации)
        """
        cursor = np.where(self.data.index.values == idx)[0][0]
        values = self.data.loc[:, name].values
        values = values[cursor - step_factor + 1: cursor + 1]
        if step_factor > 1:
            values = getattr(np, agg)(values.reshape(-1, step_factor), axis=1)
        return values[0]

    def get_current_index(self):
        return self.index
    
    def get_current_cursor(self):
        return self.cursor

In [207]:
dp = DataPoint(dataset.head(10), observation_len=10, future_points=0)

In [208]:
dp.data.index

Int64Index([1662185340, 1662185640, 1662185940, 1662186240, 1662186540,
            1662186840, 1662187140, 1662187440, 1662187740, 1662188040],
           dtype='int64', name='ts')

In [209]:
dp.get_current_index()

1662188040

In [210]:
dp.get_current_cursor()

9

In [211]:
dp.get_index_slice()

(0, 10)

In [215]:
step_factor = 1
s = dp.get_values("highest_bid", step_factor=step_factor)
print(s)

print(dp.data["highest_bid"].values[-dp.observation_len*step_factor:])

[19928.361 19913.    19908.92  19826.23  19858.441 19888.23  19876.55  19869.979 19898.2
 19884.28 ]
[19928.361 19913.    19908.92  19826.23  19858.441 19888.23  19876.55  19869.979 19898.2
 19884.28 ]

In [213]:
step_factor = 1
s = dp.get_value("highest_bid", step_factor=step_factor)
print(s)

19884.28

In [152]:
dp.get_values("highest_bid", step_factor=2, num=3)

array([19300.544 , 19308.3755, 19321.59  ])

In [112]:
dp.data.tail(8)

,dt,lowest_ask,highest_bid,asks,bids,buy_vol,sell_vol,total_vol,buy_num,sell_num,total_num
ts,,,,,,,,,,,
1662679440,2022-09-08 23:24:00,19329.950,19329.941,"{'19329.95': 0.46, '19332.01': 0.23, '19332.98...","{'19329.94': 0.46, '19327.99': 0.23, '19326.05...",0.093351,0.332515,0.425866,6,6,12
1662679740,2022-09-08 23:29:00,19328.000,19327.990,"{'19328': 0.493774, '19329.95': 0.197209, '193...","{'19327.99': 0.23, '19326.05': 0.23, '19323.16...",0.147513,0.169983,0.317496,12,10,22
1662680040,2022-09-08 23:34:00,19303.340,19303.328,"{'19303.34': 0.46, '19304.37': 0.23, '19305.33...","{'19303.33': 0.46, '19300.7': 0.229659, '19299...",0.181660,0.208626,0.390286,8,10,18
1662680340,2022-09-08 23:39:00,19300.709,19297.760,"{'19300.71': 0.46, '19302.74': 0.1, '19303.34'...","{'19297.76': 0.321161, '19295.83': 0.116558, '...",0.740906,0.555953,1.296859,14,12,26
1662680640,2022-09-08 23:44:00,19307.469,19307.460,"{'19307.47': 0.23, '19309.41': 0.46, '19311.35...","{'19307.46': 0.46, '19303.33': 0.349732, '1930...",0.659533,0.755492,1.415025,11,13,24
1662680940,2022-09-08 23:49:00,19309.299,19309.291,"{'19309.3': 0.46, '19311.31': 0.23, '19313.25'...","{'19309.29': 0.46, '19308.77': 0.163093, '1930...",0.319304,0.867603,1.186907,4,8,12
1662681240,2022-09-08 23:54:00,19319.270,19317.170,"{'19319.27': 0.451095, '19321.32': 0.23, '1932...","{'19317.17': 0.459211, '19315.01': 0.23, '1931...",1.348322,0.676910,2.025232,17,6,23
1662681540,2022-09-08 23:59:00,19326.020,19326.010,"{'19326.02': 0.293474, '19327.95': 0.229311, '...","{'19326.01': 0.002403, '19325.05': 0.23, '1932...",0.737640,0.495444,1.233084,18,8,26

In [43]:
step_factor = 2

num = 8
num_ = num * step_factor


low_bound, up_bound = dp.get_indexes(step_factor=step_factor, num=num_)
print(low_bound, up_bound)

1618 1650

In [52]:
name = "highest_bid"
values = dp.data.loc[:, name].values
values

array([19928.361, 19913.   , 19908.92 , ..., 19309.291, 19317.17 ,
       19326.01 ])

In [53]:
result = values[low_bound: up_bound]
result

array([19371.479, 19368.92 , 19332.64 , 19329.682, 19334.58 , 19320.7  ,
       19316.15 , 19333.43 , 19342.23 , 19293.602, 19304.32 , 19328.91 ,
       19325.97 , 19300.76 , 19300.012, 19320.   , 19304.08 , 19274.27 ,
       19276.791, 19258.21 , 19278.371, 19281.27 , 19295.58 , 19287.41 ,
       19297.51 , 19316.74 , 19309.201, 19311.629, 19307.49 , 19329.941,
       19327.99 , 19303.328])

In [54]:
agg = "average"
result = getattr(np, agg)(result.reshape(-1, step_factor), axis=1)
result

array([19370.1995, 19331.161 , 19327.64  , 19324.79  , 19317.916 ,
       19316.615 , 19313.365 , 19310.006 , 19289.175 , 19267.5005,
       19279.8205, 19291.495 , 19307.125 , 19310.415 , 19318.7155,
       19315.659 ])

In [209]:
dp.get_indexes()

array([1662807000, 1662807300, 1662807600, 1662807900, 1662808200,
       1662808500, 1662808800, 1662809100, 1662809400, 1662809700])

In [210]:
ss = dp.get_values(name="highest_bid", num=2, as_ndarray=True)
ss

array([21327.541, 21294.281], dtype=float32)

In [211]:
dd = dp.get_value("highest_bid", cursor = 1662797100)
dd

21284.56

In [212]:
dp.get_current_index()

1662809700

In [157]:
ss.diff().dropna().values

array([-20.488281, -33.259766], dtype=float32)

In [148]:
cursor = dp.get_indexes(num=1)
dp.get_values(cursor=cursor, num=dp.hist_len, as_ndarray=False)

,dt,lowest_ask,highest_bid,asks,bids,buy_vol,sell_vol,total_vol,buy_num,sell_num,total_num
ts,,,,,,,,,,,
1662799500,2022-09-10 08:45:00,21344.490234,21317.599609,"{'21344.49': 0.096623, '21344.78': 0.212242, '...","{'21317.6': 0.7, '21306.54': 0.234, '21297.13'...",1.143023,0.328697,1.471720,24,16,40
1662799800,2022-09-10 08:50:00,21310.361328,21309.750000,"{'21310.36': 0.204283, '21318': 0.235, '21319....","{'21309.75': 0.670705, '21307.18': 0.013668, '...",0.249728,1.624330,1.874058,9,31,40
1662800100,2022-09-10 08:55:00,21321.199219,21319.800781,"{'21321.2': 0.195339, '21326': 0.232063, '2134...","{'21319.8': 0.211053, '21300.99': 0.386166, '2...",0.834215,0.747824,1.582039,19,31,50
1662800400,2022-09-10 09:00:00,21305.599609,21296.740234,"{'21305.6': 0.196293, '21308.23': 0.210702, '2...","{'21296.74': 0.665715, '21276.67': 0.011152, '...",0.203970,1.093149,1.297119,24,27,51
1662800700,2022-09-10 09:05:00,21292.119141,21291.371094,"{'21292.12': 0.03, '21293.5': 0.235, '21295.63...","{'21291.37': 0.434304, '21283.46': 0.012226, '...",0.047145,0.374906,0.422051,8,38,46
1662801000,2022-09-10 09:10:00,21296.298828,21292.869141,"{'21296.3': 0.123634, '21307.61': 0.004343, '2...","{'21292.87': 0.234758, '21290.43': 0.235, '212...",1.571577,1.358688,2.930265,27,66,93
1662801300,2022-09-10 09:15:00,21313.320312,21312.349609,"{'21313.32': 0.235, '21315.46': 0.235, '21316....","{'21312.35': 0.7, '21311.26': 0.235, '21309': ...",0.777562,1.200628,1.978190,10,59,69
1662801600,2022-09-10 09:20:00,21337.880859,21332.740234,"{'21337.88': 0.03043, '21343.85': 0.235, '2134...","{'21332.74': 0.235, '21328.78': 0.500289, '213...",1.094926,0.835427,1.930353,15,13,28
1662801900,2022-09-10 09:25:00,21353.378906,21327.929688,"{'21353.38': 0.226739, '21355.52': 0.235, '213...","{'21327.93': 0.136858, '21327.12': 0.468816, '...",2.060175,0.863481,2.923656,22,14,36
1662802200,2022-09-10 09:30:00,21358.720703,21311.908203,"{'21358.72': 0.231831, '21363.83': 0.235, '213...","{'21311.91': 0.47, '21311.26': 0.206845, '2130...",0.259313,0.220072,0.479385,6,53,59
1662802500,2022-09-10 09:35:00,21324.939453,21313.470703,"{'21324.94': 0.228228, '21358.72': 0.231831, '...","{'21313.47': 0.323293, '21305.79': 0.09, '2130...",0.296975,0.358747,0.655722,9,16,25
1662802800,2022-09-10 09:40:00,21324.939453,21313.470703,"{'21324.94': 0.228228, '21358.72': 0.231831, '...","{'21313.47': 0.323293, '21305.17': 0.09, '2130...",0.000099,0.008160,0.008259,1,9,10
1662803100,2022-09-10 09:45:00,21357.800781,21353.349609,"{'21357.8': 0.468923, '21362.53': 0.151656, '2...","{'21353.35': 0.015089, '21352.01': 0.058879, '...",0.682175,0.388825,1.071000,34,37,71
1662803400,2022-09-10 09:50:00,21356.740234,21356.449219,"{'21356.74': 0.235, '21357.8': 0.000675, '2136...","{'21356.45': 0.02, '21355.55': 0.029916, '2135...",0.224615,0.837065,1.061680,15,28,43
1662803700,2022-09-10 09:55:00,21368.201172,21355.591797,"{'21368.2': 0.189, '21370.48': 0.098165, '2138...","{'21355.59': 0.146571, '21353.42': 0.235, '213...",0.350257,1.153433,1.503690,45,24,69
1662804000,2022-09-10 10:00:00,21367.000000,21357.791016,"{'21367': 0.189, '21375.68': 0.096577, '21380....","{'21357.79': 0.234054, '21356.71': 0.235, '213...",1.102779,0.071268,1.174047,59,14,73
1662804300,2022-09-10 10:05:00,21359.310547,21336.839844,"{'21359.31': 0.206725, '21360.29': 0.096345, '...","{'21336.84': 0.002343, '21331.22': 0.002206, '...",0.387563,0.025615,0.413178,35,8,43
1662804600,2022-09-10 10:10:00,21355.669922,21355.660156,"{'21355.67': 1.771425, '21355.8': 0.788, '2135...","{'21355.66': 0.030998, '21336.84': 0.000345, '...",0.585775,0.002054,0.587829,35,3,38
1662804900,2022-09-10 10:15:00,21279.630859,21266.458984,"{'21279.63': 0.000937, '21279.69': 1.063196, '...","{'21266.46': 0.008568, '21266.45': 0.01949, '2...",0.599119,0.385017,0.984136,36,20,56
1662805200,2022-09-10 10:20:00,21267.990234,21267.980469,"{'21267.99': 0.015289, '21268': 0.189, '21270....","{'21267.98': 0.447807, '21265.15': 0.235, '212...",0.312351,0.394930,0.707281,12,24,36
1662805500,2022-09-10 10:25:00,21303.878906,21286.849609,"{'21303.88': 1.641575, '21303.89': 0.097352, '...","{'21286.85': 0.043217, '21264.91': 0.140563, '...",0.503641,0.508784,1.012425,17,23,40
1662805800,2022-09-10 10:30:00,21320.470703,21317.720703,"{'21320.47': 0.5, '21332.5': 0.189, '21334.9':...","{'21317.72': 0.039338, '21308.26': 0.14, '2130...",0.635610,0.420498,1.056108,25,16,41
1662806100,2022-09-10 10:35:00,21315.830078,21309.990234,"{'21315.83': 0.00207, '21315.93': 0.02, '21316...","{'21309.99': 0.14, '21309.98': 0.301291, '2130...",0.765612,0.573173,1.338785,31,22,53
1662806400,2022-09-10 10:40:00,21376.900391,21359.339844,"{'21376.9': 0.378, '21383.18': 0.096719, '2138...","{'21359.34': 0.3, '21335.51': 0.002263, '21328...",0.504288,0.339062,0.843350,25,24,49
1662806700,2022-09-10 10:45:00,21344.759766,21338.919922,"{'21344.76': 0.02, '21345.23': 0.3, '21346.39'...","{'21338.92': 0.14, '21338.91': 0.2, '21338.14'...",0.239853,0.438942,0.678795,13,33,46
1662807000,2022-09-10 10:50:00,21349.400391,21344.839844,"{'21349.4': 0.01, '21357.89': 0.14, '21357.9':...","{'21344.84': 0.60053, '21344.83': 0.002403, '2...",0.596947,0.237970,0.834917,24,17,41
1662807300,2022-09-10 10:55:00,21325.669922,21315.691406,"{'21325.67': 0.01, '21325.8': 0.001159, '21325...","{'21315.69': 0.207693, '21315.68': 0.6, '21315...",1.290339,1.059897,2.350236,18,21,39
1662807600,2022-09-10 11:00:00,21340.060547,21333.199219,"{'21340.06': 0.000944, '21340.07': 0.01, '2134...","{'21333.2': 0.14, '21333.19': 0.55, '21333.18'...",1.383947,1.262327,2.646274,14,17,31
1662807900,2022-09-10 11:05:00,21336.771484,21326.640625,"{'21336.77': 0.000953, '21336.78': 0.01, '2135...","{'21326.64': 0.002804, '21326.24': 0.55, '2130...",0.434972,0.690435,1.125407,7,14,21
1662808200,2022-09-10 11:10:00,21321.751953,21316.730469,"{'21321.75': 0.01, '21324.24': 0.05, '21324.25...","{'21316.73': 7.8e-05, '21311.94': 0.687177, '2...",1.898726,1.150789,3.049515,24,37,61
1662808500,2022-09-10 11:15:00,21371.119141,21354.689453,"{'21371.12': 0.01, '21378.99': 0.14, '21379': ...","{'21354.69': 0.14, '21354.68': 0.468187, '2135...",1.301409,1.414153,2.715562,20,25,45
1662808800,2022-09-10 11:20:00,21363.398438,21358.591797,"{'21363.4': 0.05354, '21366.4': 0.01, '21366.8...","{'21358.59': 0.00117, '21354.55': 0.14, '21354...",1.605212,0.909298,2.514510,19,13,32
1662809100,2022-09-10 11:25:00,21351.251953,21348.029297,"{'21351.25': 0.01, '21352.65': 0.1, '21361.91'...","{'21348.03': 0.544936, '21347.99': 0.000486, '...",1.572732,1.519187,3.091919,17,33,50
1662809400,2022-09-10 11:30:00,21335.001953,21327.541016,"{'21335': 0.1, '21335.01': 0.00098, '21335.79'...","{'21327.54': 0.14, '21327.53': 0.55, '21322.34...",1.316541,1.773979,3.090520,21,30,51
1662809700,2022-09-10 11:35:00,21307.771484,21294.281250,"{'21307.77': 0.01, '21316.5': 0.189, '21321.21...","{'21294.28': 0.14, '21294.27': 0.469515, '2129...",1.292653,1.073682,2.366335,18,17,35

In [141]:
import json

In [146]:
cursor_prev = dp.get_indexes(num=1)
data_raw = dp.get_values(name="asks", num=1, cursor=cursor_prev, as_ndarray=False)
data_raw

{'21307.77': 0.01,
 '21316.5': 0.189,
 '21321.21': 0.002199,
 '21325.77': 0.7,
 '21327.7': 0.002551,
 '21330.13': 0.00247,
 '21331.14': 0.001882,
 '21333.7': 0.8,
 '21340.02': 0.14,
 '21346': 0.394,
 '21363.4': 0.00354,
 '21365': 0.000411,
 '21400': 0.04,
 '21406': 0.03,
 '21409.16': 0.002787,
 '21414.06': 0.003403,
 '21418.9': 0.001191,
 '21418.94': 0.00116,
 '21421.21': 0.004,
 '21450': 0.008464,
 '21450.93': 3.956,
 '21464.38': 0.003394,
 '21500': 0.001,
 '21514.81': 0.003387,
 '21565.37': 0.003378,
 '21574.82': 0.031452,
 '21576.76': 0.2,
 '21578.64': 0.030488,
 '21587.36': 0.028802,
 '21593.51': 0.061227,
 '21593.55': 0.09926,
 '21594.98': 0.09926,
 '21600': 0.188825,
 '21602.57': 1.964,
 '21604.16': 6.7e-05,
 '21605.92': 0.000852,
 '21616.04': 0.003373,
 '21618.9': 0.012761,
 '21624.38': 0.031118,
 '21624.39': 0.005516,
 '21626.11': 0.031118,
 '21640': 5e-05,
 '21650': 0.089387,
 '21654': 0.52487,
 '21666.84': 0.003361,
 '21672.01': 0.001153,
 '21673.71': 0.009192,
 '21685.05': 0.00023,
 '21686.68': 7.9e-05,
 '21689': 0.1,
 '21700': 0.001289,
 '21700.04': 0.109918,
 '21707.54': 0.000312,
 '21708.34': 9.6e-05,
 '21714.06': 0.000207,
 '21717.75': 0.003354,
 '21723.08': 0.01,
 '21740.1': 0.0046,
 '21762.61': 0.000249,
 '21768.79': 0.003346,
 '21770.57': 0.05,
 '21774.06': 0.00017,
 '21777': 0.3,
 '21777.71': 4.9e-05,
 '21784.06': 0.000229,
 '21795.2': 0.068059,
 '21795.83': 0.000458,
 '21800': 0.09222,
 '21822.7': 0.00025,
 '21831.17': 0.012,
 '21840.1': 0.004579,
 '21841.78': 0.006004,
 '21843.88': 0.014313,
 '21850': 0.048543,
 '21854.06': 0.000228,
 '21862.48': 0.012761,
 '21872.01': 0.001143,
 '21884.06': 0.000274,
 '21886.77': 0.005046,
 '21889': 5e-05,
 '21900': 0.004637,
 '21903.13': 0.0058,
 '21905.73': 0.000273,
 '21907.54': 0.000312,
 '21917.11': 0.003675,
 '21920': 1.0,
 '21922.84': 0.008502,
 '21933.56': 0.058479,
 '21940.1': 0.004558,
 '21965': 0.001047,
 '21984': 0.2,
 '21985': 0.076184,
 '21985.05': 0.000227,
 '21995.73': 0.000272,
 '22000': 0.266084,
 '22038.7': 0.019184,
 '22040.1': 0.004538,
 '22082.68': 0.013874,
 '22090.9': 0.000226,
 '22095.83': 0.000452,
 '22100': 0.002242,
 '22104': 5e-05,
 '22108.81': 0.012761,
 '22136.04': 0.000309,
 '22140.1': 0.004517,
 '22141.64': 8.7e-05,
 '22147.12': 0.008502,
 '22150': 0.927803,
 '22150.9': 0.00027,
 '22158': 0.072433,
 '22162.61': 0.00025,
 '22178.3': 0.002275,
 '22185.05': 0.000225,
 '22190.9': 0.000315,
 '22200': 0.001286,
 '22220.9': 0.00027,
 '22222': 0.000534,
 '22229.67': 0.000319,
 '22239.82': 0.00012,
 '22240.1': 0.004497,
 '22290': 0.060553,
 '22300': 0.097962,
 '22325': 6e-05,
 '22330.9': 0.000313,
 '22340.1': 0.004477,
 '22350.9': 0.000268,
 '22357.91': 0.012761,
 '22395.83': 0.000446,
 '22400': 0.083801,
 '22410': 0.05,
 '22414.55': 4.9e-05,
 '22419.62': 0.057211,
 '22427': 0.02,
 '22440.1': 0.004457,
 '22441.84': 0.04521,
 '22460': 1.0,
 '22471.15': 0.000445,
 '22487.33': 0.033605,
 '22500': 0.046124,
 '22506.04': 0.000266,
 '22512': 0.001,
 '22530.7': 0.000462,
 '22540.1': 0.004437,
 '22548': 7e-05,
 '22550': 0.085764,
 '22562.61': 0.00025,
 '22588': 0.2,
 '22607.32': 0.002422,
 '22609.82': 0.012761,
 '22616.04': 0.000265}

In [97]:
orderbook_prev = json.loads(data_raw.replace("\'", "\""))

1

In [102]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [81]:
current_idx = 1662811200
n=-1


if n > 0:
    period = data.index[0] - data.index[1]
    stop = current_idx + (period * n)
else:
    period = data.index[1] - data.index[0]
    stop = current_idx - (period * n)

idxs = np.arange(current_idx, stop, period)
idxs

array([1662811200])

In [82]:
def get_values(name=None, cursor=None, step_factor=1, num=None):

    if cursor is None:
        cursor = current_idx

    if name is None:
        name = data.columns
    
    if num is None:
        num = 4 # observation 
        
    period = (data.index[1] - data.index[0]) * step_factor

    if num > 0:
        stop = cursor - (period * (num-1))
        idxs = np.arange(stop, cursor+period, period)
    else:
        stop = cursor - (period * num)
        idxs = np.arange(cursor, stop, period)
        
    df = data.loc[idxs, name]
    display(df)

In [100]:
def get_indexes(cursor=None, step_factor=1, num=None):
         
    if cursor is None:
        cursor = current_idx

    if num is None:
        num = 4

    period = (data.index[1] - data.index[0]) * step_factor

    if num > 0:
        stop = cursor - (period * (num-1))
        idxs = np.arange(stop, cursor+period, period)
    else:
        stop = cursor - (period * num)
        idxs = np.arange(cursor, stop, period)

    return idxs

get_indexes()

array([1662810300, 1662810600, 1662810900, 1662811200])

## Datapoint Factory

In [9]:
from data_point import DataPointFactory

In [15]:
n_observation_points = 5
n_future_points = 0
n_history_points = 2
period = 300

dpf = DataPointFactory(
    dataset=data, 
    period=period, 
    n_observation_points=n_observation_points,
    n_history_points = n_history_points,
    n_future_points=n_future_points
)

In [16]:
dp = dpf.get_current_step()

In [17]:
dp.__dict__

{'data':                             dt    lowest_ask   highest_bid  \
 ts
 1662796500 2022-09-10 07:55:00  21352.500000  21352.310547
 1662796800 2022-09-10 08:00:00  21353.130859  21274.349609
 1662797100 2022-09-10 08:05:00  21326.000000  21284.560547
 1662797400 2022-09-10 08:10:00  21325.759766  21293.109375
 1662797700 2022-09-10 08:15:00  21304.380859  21281.400391
 1662798000 2022-09-10 08:20:00  21286.029297  21271.300781
 1662798300 2022-09-10 08:25:00  21314.351562  21296.478516

                                                          asks  \
 ts
 1662796500  {'21352.5': 0.394, '21379.27': 0.036275, '2138...
 1662796800  {'21353.13': 0.480706, '21354.98': 0.280799, '...
 1662797100  {'21326': 0.690315, '21339.2': 0.020079, '2134...
 1662797400  {'21325.76': 0.689794, '21345.84': 0.235, '213...
 1662797700  {'21304.38': 0.07549, '21325.76': 0.7, '21338....
 1662798000  {'21286.03': 0.087013, '21307.8': 0.788, '2132...
 1662798300  {'21314.35': 0.094414, '21325.76': 0.694458, '...

                                                          bids   buy_vol  \
 ts
 1662796500  {'21352.31': 0.000629, '21352.3': 0.002616, '2...  1.555272
 1662796800  {'21274.35': 0.095289, '21252.3': 0.003414, '2...  0.109545
 1662797100  {'21284.56': 0.097647, '21252.3': 0.003414, '2...  0.346015
 1662797400  {'21293.11': 0.001296, '21291.5': 0.7, '21254....  2.672747
 1662797700  {'21281.4': 0.7, '21276.31': 0.097267, '21252....  1.764921
 1662798000  {'21271.3': 0.098975, '21269.07': 0.470095, '2...  1.283036
 1662798300  {'21296.48': 0.098411, '21293.4': 0.460593, '2...  2.722896

             sell_vol  total_vol  buy_num  sell_num  total_num
 ts
 1662796500  0.011891   1.567163       54        11         65
 1662796800  0.013863   0.123408       42         8         50
 1662797100  0.389333   0.735348      158        35        193
 1662797400  0.677586   3.350333      107       106        213
 1662797700  0.645449   2.410370       73       115        188
 1662798000  0.453469   1.736505       69        41        110
 1662798300  2.042861   4.765757       63        32         95  ,
 'fut_len': 0,
 'obs_len': 5,
 'hist_len': 2,
 'current_idx': 1662798300,
 'start_idx': 1662797100,
 'period': 300}

In [61]:
dp, done = dpf.get_next_step()
print(done)

True

In [62]:
dp.data

,dt,lowest_ask,highest_bid,asks,bids,buy_vol,sell_vol,total_vol,buy_num,sell_num,total_num
ts,,,,,,,,,,,
1662809400,2022-09-10 11:30:00,21335.001953,21327.541016,"{'21335': 0.1, '21335.01': 0.00098, '21335.79'...","{'21327.54': 0.14, '21327.53': 0.55, '21322.34...",1.316541,1.773979,3.090520,21,30,51
1662809700,2022-09-10 11:35:00,21307.771484,21294.281250,"{'21307.77': 0.01, '21316.5': 0.189, '21321.21...","{'21294.28': 0.14, '21294.27': 0.469515, '2129...",1.292653,1.073682,2.366335,18,17,35
1662810000,2022-09-10 11:40:00,21298.380859,21290.628906,"{'21298.38': 0.01, '21298.73': 0.00247, '21299...","{'21290.63': 0.69, '21290.6': 1.413195, '21280...",1.122753,1.586319,2.709072,15,17,32
1662810300,2022-09-10 11:45:00,21300.250000,21298.650391,"{'21300.25': 0.00073, '21300.26': 0.15, '21307...","{'21298.65': 0.14, '21297.14': 0.69, '21292.09...",1.888513,1.531294,3.419807,19,19,38
1662810600,2022-09-10 11:50:00,21295.941406,21287.980469,"{'21295.94': 0.01, '21299.02': 0.15, '21308.22...","{'21287.98': 0.14, '21287.97': 0.55, '21287.96...",2.045997,1.473329,3.519326,26,15,41
1662810900,2022-09-10 11:55:00,21279.521484,21277.070312,"{'21279.52': 0.001214, '21282.04': 0.15, '2128...","{'21277.07': 0.55, '21273.72': 1.426844, '2126...",0.661370,1.257566,1.918936,10,12,22
1662811200,2022-09-10 12:00:00,21288.179688,21279.009766,"{'21288.18': 1.370121, '21288.19': 0.7, '21289...","{'21279.01': 0.000223, '21273.43': 0.14, '2127...",1.432162,1.484592,2.916754,19,21,40